// actionType.js
const actionTypes = Object.freeze({
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",

  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

  CREATE_CV_REQUEST: "CREATE_CV_REQUEST",
  CREATE_CV_SUCCESS: "CREATE_CV_SUCCESS",
  CREATE_CV_FAILURE: "CREATE_CV_FAILURE",

  UPDATE_ALL_NOT_DEFAULT_CV_REQUEST: "UPDATE_ALL_NOT_DEFAULT_CV_REQUEST",
  UPDATE_ALL_NOT_DEFAULT_CV_SUCCESS: "UPDATE_ALL_NOT_DEFAULT_CV_SUCCESS",
  UPDATE_ALL_NOT_DEFAULT_CV_FAILURE: "UPDATE_ALL_NOT_DEFAULT_CV_FAILURE",

  FETCH_ALL_CV_BY_USER_ID_REQUEST: "FETCH_ALL_CV_BY_USER_ID_REQUEST",
  FETCH_ALL_CV_BY_USER_ID_SUCCESS: "FETCH_ALL_CV_BY_USER_ID_SUCCESS",
  FETCH_ALL_CV_BY_USER_ID_FAILURE: "FETCH_ALL_CV_BY_USER_ID_FAILURE",

  SET_DEFAULT_CV_REQUEST: "SET_DEFAULT_CV_REQUEST",
  SET_DEFAULT_CV_SUCCESS: "SET_DEFAULT_CV_SUCCESS",
  SET_DEFAULT_CV_FAILURE: "SET_DEFAULT_CV_FAILURE",

  CREATE_JOB_REQUEST: "CREATE_JOB_REQUEST",
  CREATE_JOB_SUCCESS: "CREATE_JOB_SUCCESS",
  CREATE_JOB_FAILURE: "CREATE_JOB_FAILURE",

  FETCH_ALL_JOB_BY_RECRUITER_ID_REQUEST:
    "FETCH_ALL_JOB_BY_RECRUITER_ID_REQUEST",
  FETCH_ALL_JOB_BY_RECRUITER_ID_SUCCESS:
    "FETCH_ALL_JOB_BY_RECRUITER_ID_SUCCESS",
  FETCH_ALL_JOB_BY_RECRUITER_ID_FAILURE:
    "FETCH_ALL_JOB_BY_RECRUITER_ID_FAILURE",

  FETCH_ALL_JOB_REQUEST: "FETCH_ALL_JOB_REQUEST",
  FETCH_ALL_JOB_SUCCESS: "FETCH_ALL_JOB_SUCCESS",
  FETCH_ALL_JOB_FAILURE: "FETCH_ALL_JOB_FAILURE",

  CREATE_APPLICATION_REQUEST: "CREATE_APPLICATION_REQUEST",
  CREATE_APPLICATION_SUCCESS: "CREATE_APPLICATION_SUCCESS",
  CREATE_APPLICATION_FAILURE: "CREATE_APPLICATION_FAILURE",

  FETCH_ALL_APPLI_BY_RECRUI_REQUEST: "FETCH_ALL_APPLI_BY_RECRUI_REQUEST",
  FETCH_ALL_APPLI_BY_RECRUI_SUCCESS: "FETCH_ALL_APPLI_BY_RECRUI_SUCCESS",
  FETCH_ALL_APPLI_BY_RECRUI_FAILURE: "FETCH_ALL_APPLI_BY_RECRUI_FAILURE",

  FETCH_ALL_USER_REQUEST: "FETCH_ALL_USER_REQUEST",
  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAILURE: "FETCH_ALL_USER_FAILURE",

  FETCH_ALL_APPLICATION_BY_USER_ID_REQUEST:
    "FETCH_ALL_APPLICATION_BY_USER_ID_REQUEST",
  FETCH_ALL_APPLICATION_BY_USER_ID_SUCCESS:
    "FETCH_ALL_APPLICATION_BY_USER_ID_SUCCESS",
  FETCH_ALL_APPLICATION_BY_USER_ID_FAILURE:
    "FETCH_ALL_APPLICATION_BY_USER_ID_FAILURE",
});

export default actionTypes;
